export const STORE_INFO_REQUEST = "STORE_INFO_REQUEST";
export const STORE_INFO_SUCCESS = "STORE_INFO_SUCCESS";
export const STORE_INFO_FAILURE = "STORE_INFO_FAILURE";
export const FILTER_STORE_PRODUCTS = "FILTER_STORE_PRODUCTS";
export const GET_ALL_STORE_PRODUCTS_REQUEST = "GET_ALL_STORE_PRODUCTS_REQUEST";
export const GET_ALL_STORE_PRODUCTS_SUCCESS = "GET_ALL_STORE_PRODUCTS_SUCCESS";
export const GET_ALL_STORE_PRODUCTS_FAILURE = "GET_ALL_STORE_PRODUCTS_FAILURE";
