export const STORE_INFO_REQUEST = "STORE_INFO_REQUEST";
export const STORE_INFO_SUCCESS = "STORE_INFO_SUCCESS";
export const STORE_INFO_FAILURE = "STORE_INFO_FAILURE";
export const FILTER_STORE_PRODUCTS = "FILTER_STORE_PRODUCTS";
export const GET_ALL_STORE_PRODUCTS_REQUEST = "GET_ALL_STORE_PRODUCTS_REQUEST";
export const GET_ALL_STORE_PRODUCTS_SUCCESS = "GET_ALL_STORE_PRODUCTS_SUCCESS";
export const GET_ALL_STORE_PRODUCTS_FAILURE = "GET_ALL_STORE_PRODUCTS_FAILURE";
export const ADD_PRODUCT_TO_STORE_REQUEST = "ADD_PRODUCT_TO_STORE_REQUEST";
export const ADD_PRODUCT_TO_STORE_SUCCESS = "ADD_PRODUCT_TO_STORE_SUCCESS";
export const ADD_PRODUCT_TO_STORE_FAILURE = "ADD_PRODUCT_TO_STORE_FAILURE";
export const REMOVE_PRODUCT_FROM_STORE_REQUEST =
  "REMOVE_PRODUCT_TO_STORE_REQUEST";
export const REMOVE_PRODUCT_FROM_STORE_SUCCESS =
  "REMOVE_PRODUCT_TO_STORE_SUCCESS";
export const REMOVE_PRODUCT_FROM_STORE_FAILURE =
  "REMOVE_PRODUCT_TO_STORE_FAILURE";
export const EDIT_PRODUCT_FROM_STORE_REQUEST =
  "EDIT_PRODUCT_FROM_STORE_REQUEST";
export const EDIT_PRODUCT_FROM_STORE_SUCCESS =
  "EDIT_PRODUCT_FROM_STORE_SUCCESS";
export const EDIT_PRODUCT_FROM_STORE_FAILURE =
  "EDIT_PRODUCT_FROM_STORE_FAILURE";
export const GET_STORE_ROLES_REQUEST = "GET_STORE_ROLES_REQUEST";
export const GET_STORE_ROLES_SUCCESS = "GET_STORE_ROLES_SUCCESS";
export const GET_STORE_ROLES_FAILURE = "GET_STORE_ROLES_FAILURE";
export const GET_STORE_SUBORDINATES_REQUEST = "GET_STORE_SUBORDINATES_REQUEST";
export const GET_STORE_SUBORDINATES_SUCCESS = "GET_STORE_SUBORDINATES_SUCCESS";
export const GET_STORE_SUBORDINATES_FAILURE = "GET_STORE_SUBORDINATES_FAILURE";
export const ADD_STORE_OWNER_REQUEST = "ADD_STORE_OWNER_REQUEST";
export const ADD_STORE_OWNER_SUCCESS = "ADD_STORE_OWNER_SUCCESS";
export const ADD_STORE_OWNER_FAILURE = "ADD_STORE_OWNER_FAILURE";
export const ADD_STORE_MANAGER_REQUEST = "ADD_STORE_MANAGER_REQUEST";
export const ADD_STORE_MANAGER_SUCCESS = "ADD_STORE_MANAGER_SUCCESS";
export const ADD_STORE_MANAGER_FAILURE = "ADD_STORE_MANAGER_FAILURE";
export const REMOVE_STORE_MANAGER_REQUEST = "REMOVE_STORE_MANAGER_REQUEST";
export const REMOVE_STORE_MANAGER_SUCCESS = "REMOVE_STORE_MANAGER_SUCCESS";
export const REMOVE_STORE_MANAGER_FAILURE = "REMOVE_STORE_MANAGER_FAILURE";
export const REMOVE_STORE_OWNER_REQUEST = "REMOVE_STORE_OWNER_REQUEST";
export const REMOVE_STORE_OWNER_SUCCESS = "REMOVE_STORE_OWNER_SUCCESS";
export const REMOVE_STORE_OWNER_FAILURE = "REMOVE_STORE_OWNER_FAILURE";
export const GET_STORE_POLICY_REQUEST = "GET_STORE_POLICY_REQUEST";
export const GET_STORE_POLICY_SUCCESS = "GET_STORE_POLICY_SUCCESS";
export const GET_STORE_POLICY_FAILURE = "GET_STORE_POLICY_FAILURE";
export const ADD_STORE_POLICY_ROOT_REQUEST = "ADD_POLICY_ROOT_REQUEST";
export const ADD_STORE_POLICY_ROOT_SUCCESS = "ADD_POLICY_ROOT_SUCCESS";
export const ADD_STORE_POLICY_ROOT_FAILURE = "ADD_POLICY_ROOT_FAILURE";
export const ADD_STORE_SUB_POLICY_REQUEST = "ADD_SUB_POLICY_REQUEST";
export const ADD_STORE_SUB_POLICY_SUCCESS = "ADD_SUB_POLICY_SUCCESS";
export const ADD_STORE_SUB_POLICY_FAILURE = "ADD_SUB_POLICY_FAILURE";
export const REMOVE_STORE_POLICY_REQUEST = "REMOVE_SUB_POLICY_REQUEST";
export const REMOVE_STORE_POLICY_SUCCESS = "REMOVE_SUB_POLICY_SUCCESS";
export const REMOVE_STORE_POLICY_FAILURE = "REMOVE_SUB_POLICY_FAILURE";
