export const STORE_INFO_REQUEST = "STORE_INFO_REQUEST";
export const STORE_INFO_SUCCESS = "STORE_INFO_SUCCESS";
export const STORE_INFO_FAILURE = "STORE_INFO_FAILURE";
export const FILTER_STORE_PRODUCTS = "FILTER_STORE_PRODUCTS";
export const GET_ALL_STORE_PRODUCTS_REQUEST = "GET_ALL_STORE_PRODUCTS_REQUEST";
export const GET_ALL_STORE_PRODUCTS_SUCCESS = "GET_ALL_STORE_PRODUCTS_SUCCESS";
export const GET_ALL_STORE_PRODUCTS_FAILURE = "GET_ALL_STORE_PRODUCTS_FAILURE";
export const ADD_PRODUCT_TO_STORE_REQUEST = "ADD_PRODUCT_TO_STORE_REQUEST";
export const ADD_PRODUCT_TO_STORE_SUCCESS = "ADD_PRODUCT_TO_STORE_SUCCESS";
export const ADD_PRODUCT_TO_STORE_FAILURE = "ADD_PRODUCT_TO_STORE_FAILURE";
export const REMOVE_PRODUCT_FROM_STORE_REQUEST =
  "REMOVE_PRODUCT_TO_STORE_REQUEST";
export const REMOVE_PRODUCT_FROM_STORE_SUCCESS =
  "REMOVE_PRODUCT_TO_STORE_SUCCESS";
export const REMOVE_PRODUCT_FROM_STORE_FAILURE =
  "REMOVE_PRODUCT_TO_STORE_FAILURE";
export const EDIT_PRODUCT_FROM_STORE_REQUEST =
  "EDIT_PRODUCT_FROM_STORE_REQUEST";
export const EDIT_PRODUCT_FROM_STORE_SUCCESS =
  "EDIT_PRODUCT_FROM_STORE_SUCCESS";
export const EDIT_PRODUCT_FROM_STORE_FAILURE =
  "EDIT_PRODUCT_FROM_STORE_FAILURE";
