export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILURE = "USER_INFO_FAILURE";
export const USER_CART_REQUEST = "USER_CART_REQUEST";
export const USER_CART_SUCCESS = "USER_CART_SUCCESS";
export const USER_CART_FAILURE = "USER_CART_FAILURE";
export const ADD_PRODUCT_TO_BASKET_REQUEST = "ADD_PRODUCT_TO_BASKET_REQUEST";
export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const ADD_PRODUCT_TO_BASKET_FAILURE = "ADD_PRODUCT_TO_BASKET_FAILURE";
export const ADD_PRODUCT_WITH_BASKET_REQUEST =
  "ADD_PRODUCT_WITH_BASKET_REQUEST";
export const ADD_PRODUCT_WITH_BASKET_SUCCESS =
  "ADD_PRODUCT_WITH_BASKET_SUCCESS";
export const ADD_PRODUCT_WITH_BASKET_FAILURE =
  "ADD_PRODUCT_WITH_BASKET_FAILURE";
