export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILURE = "USER_INFO_FAILURE";
export const USER_CART_REQUEST = "USER_CART_REQUEST";
export const USER_CART_SUCCESS = "USER_CART_SUCCESS";
export const USER_CART_FAILURE = "USER_CART_FAILURE";
export const ADD_PRODUCT_TO_BASKET_REQUEST = "ADD_PRODUCT_TO_BASKET_REQUEST";
export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const ADD_PRODUCT_TO_BASKET_FAILURE = "ADD_PRODUCT_TO_BASKET_FAILURE";
export const ADD_PRODUCT_WITH_BASKET_REQUEST =
  "ADD_PRODUCT_WITH_BASKET_REQUEST";
export const ADD_PRODUCT_WITH_BASKET_SUCCESS =
  "ADD_PRODUCT_WITH_BASKET_SUCCESS";
export const ADD_PRODUCT_WITH_BASKET_FAILURE =
  "ADD_PRODUCT_WITH_BASKET_FAILURE";
export const REMOVE_PRODUCT_FROM_BASKET_REQUEST =
  "REMOVE_PRODUCT_FROM_BASKET_REQUEST";
export const REMOVE_PRODUCT_FROM_BASKET_SUCCESS =
  "REMOVE_PRODUCT_FROM_BASKET_SUCCESS";
export const REMOVE_PRODUCT_FROM_BASKET_FAILURE =
  "REMOVE_PRODUCT_FROM_BASKET_FAILURE";
export const USER_ROLES_REQUEST = "USER_ROLES_REQUEST";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAILURE = "USER_ROLES_FAILURE";
export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAILURE = "ADD_STORE_FAILURE";
export const USER_STORE_ROLE_REQUEST = "USER_STORE_ROLE_REQUEST";
export const USER_STORE_ROLE_SUCCESS = "USER_STORE_ROLE_SUCCESS";
export const USER_STORE_ROLE_FAILURE = "USER_STORE_ROLE_FAILURE";
export const START_WEB_SOCKET_CONNECTION = "START_WEB_SOCKET_CONNECTION";
export const CLOSE_WEB_SOCKET_CONNECTION = "CLOSE_WEB_SOCKET_CONNECTION";
export const RECIEVE_REGULAR_NOTIFICATION = "RECIEVE_REGULAR_NOTIFICATION";
export const RECIEVE_ROLE_DISMISSAL_NOTIFICATION =
  "RECIEVE_ROLE_DISMISSAL_NOTIFICATION";

export const RECEIVE_STORE_PURCHASE_NOTIFICATION = "RECEIVE_STORE_PURCHASE_NOTIFICATION";
export const SEE_NOTIFICATION = "SEE_NOTIFICATION";
export const ADD_PRODUCT_TO_BASKET_AS_GUEST = "ADD_PRODUCT_TO_BASKET_AS_GUEST";
export const ADD_PRODUCT_WITH_BASKET_AS_GUEST =
  "ADD_PRODUCT_WITH_BASKET_AS_GUEST";
export const REMOVE_PRODUCT_FROM_BASKET_AS_GUEST =
  "REMOVE_PRODUCT_FROM_BASKET_AS_GUEST";
export const CHANGE_PRODUCT_AMOUNT_IN_BASKET =
  "CHANGE_PRODUCT_AMOUNT_IN_BASKET";
export const SUBMIT_PAYMENT_INFO = "SUBMIT_PAYMENT_INFO";
export const SUBMIT_DELIVERY_INFO = "SUBMIT_DELIVERY_INFO";
export const CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST";
export const CREATE_PURCHASE_SUCCESS = "CREATE_PURCHASE_SUCCESS";
export const CREATE_PURCHASE_FAILURE = "CREATE_PURCHASE_FAILURE";
export const GET_CART_DISCOUNTED_PRICE_REQUEST =
  "GET_CART_DISCOUNTED_PRICE_REQUEST";
export const GET_CART_DISCOUNTED_PRICE_SUCCESS =
  "GET_CART_DISCOUNTED_PRICE_SUCCESS";
export const GET_CART_DISCOUNTED_PRICE_FAILURE =
  "GET_CART_DISCOUNTED_PRICE_FAILURE";
